### ISSUE TITLE
커밋 권한 주실 수 있나요

### ISSUE THREAD

**Issue by jc5201** [shimika/StarlightStageProducer#3]
신데페스 아이돌 관련해서 수정을 했는데 권한이 없어서 업로드를 못하네요.
일단 포크해서 쓰고있긴 한데 시미카님 프로젝트에 합치는게 나중 업데이트 생각하면 더 좋을 것 같네요.

**Comment by widian** [comment]
pull request 를 하시면 될것같습니다.

**Comment by jc5201** [comment]
contributor에 포함이 되어있지 않아서 push부터 안됩니다

**Comment by jc5201** [comment]
아 다른 포크에서 pull request를 할 수 있군요
