### ISSUE TITLE
윈10에서 작동을 안합니다

### ISSUE THREAD

**Issue by dokimyj** [shimika/StarlightStageProducer#5]
크래시 나면서 프로그램 자체가 꺼지네요;
잘 쓰다 한달쯤 전부터 아예 켜지를 못했는데
오늘 오랜만에 켜니까 아예 작동불능...
윈10 업데이트와 관련된 충돌인지 모르겠네요

**Comment by yhs0602** [comment]
카드 검색이 안돼요

**Comment by jc5201** [comment]
@KYHSGeekCode https://github.com/jc5201/StarlightStageProducer/releases/tag/1.4.0 이 파일로 실행했을 때도 안되면 다시 댓글 남겨 주세요.

**Comment by yhs0602** [comment]
@jc5201 감사합니다. 정상적으로 다운로드하네요. ((센터/)스킬이 조금 이상하군요;;)
