### ISSUE TITLE
DB다운로드 오류

### ISSUE THREAD

**Issue by moonphase97** [shimika/StarlightStageProducer#6]
윈10 최신환경이고 실행시 예전처럼 크래시는 없지만 DB를 불러오지 못합니다. 다운로드를 한번 더 누르면 계산중만 계속 뜨네요.

**Comment by jc5201** [comment]
업데이트가 중단된 이후 인벤 페이지 구조 변경 때문에 생긴 문제인 것 같습니다.

**Comment by jc5201** [comment]
오류가 생기지 않도록 고쳐서 pull request는 날려 놓겠습니다. 다만 16년 11월 이후에 새로 생긴 스킬/센터 스킬을 가진 아이돌은 계산에 제대로 반영되지 않을 수 있습니다.

**Comment by jc5201** [comment]
https://github.com/jc5201/StarlightStageProducer/releases/download/1.3.9/SSProducer.zip
merge 되기 전 이 파일로 받아서 쓰셔도 됩니다.
센터스킬은 반영했고 스킬은 업데이트하지 않았습니다.

**Comment by moonphase97** [comment]
유지보수로 고생많으십니다. 역시 url변경돼서 문제였군요. 감사히 쓰겠습니다:)

**Comment by moonphase97** [comment]
카드 이름이 공란이 되는 버그가 있네요
